@startuml
title ETurismo - Conceptual Design

top to bottom direction

skinparam shadowing false
skinparam defaultTextAlignment center
skinparam nodesep 55
skinparam ranksep 65
skinparam linetype ortho

skinparam rectangle {
    BackgroundColor white
    BorderColor black
    RoundCorner 10
}

skinparam database {
    BackgroundColor white
    BorderColor black
}

' =====================================
' USERS
' =====================================

rectangle "TOURIST / USER" as User
rectangle "ADMINISTRATOR" as Admin

User -[hidden]right-> Admin


' =====================================
' ACCESS PLATFORM
' =====================================

rectangle "ETURISMO\nMOBILE APPLICATION" as Mobile
rectangle "ADMIN\nWEB DASHBOARD" as Dashboard

Mobile -[hidden]right-> Dashboard

User --> Mobile
Admin --> Dashboard


' =====================================
' ETURISMO
' =====================================

rectangle "ETURISMO SYSTEM" {

    rectangle "User\nManagement" as F1

    rectangle "Artifact\nExploration" as F2

    rectangle "QR Code\nScanning" as F3

    rectangle "Multilingual Content\n& Audio" as F4

    rectangle "Events &\nAnnouncements" as F5

    rectangle "Feedback &\nRatings" as F6


    ' Alignment
    F1 -[hidden]right-> F2
    F2 -[hidden]right-> F3

    F4 -[hidden]right-> F5
    F5 -[hidden]right-> F6

    F1 -[hidden]down-> F4
    F2 -[hidden]down-> F5
    F3 -[hidden]down-> F6
}


' =====================================
' ACCESS TO SYSTEM
' =====================================

Mobile --> F2 : Access
Dashboard --> F1 : Manage


' =====================================
' DATABASE
' =====================================

database "SYSTEM DATABASE" as DB

F1 --> DB
F2 --> DB
F3 --> DB
F4 --> DB
F5 --> DB
F6 --> DB

@enduml